/**
 * Biomes Config Registry — the single source of truth for map types.
 * 
 * Adding a new biome = add an entry here.
 * Adding a new feature to a biome = add it to that biome's features array.
 * No changes needed in GameCanvas, GameEngine, or WorldGenerator.
 */

import { TerrainType } from '../types';
import {
    drawTree, drawMountain, drawWater,
    drawSandGround, drawSnowGround, drawGrassGround,
    drawRoad, drawMine, drawFactory
} from './TerrainRenderer';

export type MapType = 'EMPTY' | 'FOREST' | 'DESERT' | 'FROZEN';

/** A draw function signature for terrain features */
export type TerrainDrawFunction = (
    ctx: CanvasRenderingContext2D,
    sx: number, sy: number,
    size: number,
    timeOrColor?: number | string
) => void;

/** A draw function signature for ground tiles */
export type GroundDrawFunction = (
    ctx: CanvasRenderingContext2D,
    sx: number, sy: number,
    size: number
) => void;

/** Configuration for a single terrain feature within a biome */
export interface TerrainFeature {
    /** Which TerrainType this generates in the world */
    terrain: TerrainType;
    /** Canvas draw function from TerrainRenderer */
    draw: TerrainDrawFunction;
    /** Noise parameters for procedural placement */
    noise: {
        scale: number;
        threshold: number;
        offset?: number;  // Seed offset for this layer
    };
    /** Does this terrain block movement? (Walls, water) */
    isBlocking?: boolean;
    /** Is this a vertical prop? (Trees, mountains — depth-sorted with units) */
    isVertical?: boolean;
    /** Interactive gameplay type */
    gameplay?: 'ROAD' | 'MINE' | 'FACTORY';
}

/** Full configuration for a biome */
export interface BiomeConfig {
    /** Board tile color A (dark squares) */
    tileA: string;
    /** Board tile color B (light squares) */
    tileB: string;
    /** Default ground draw for non-feature tiles (optional) */
    groundDraw?: GroundDrawFunction;
    /** Terrain features generated by noise */
    features: TerrainFeature[];
}

// ============================================================
// THE REGISTRY — Add new biomes here
// ============================================================

export const BIOME_CONFIGS: Partial<Record<MapType, BiomeConfig>> = {
    FOREST: {
        tileA: '#1a2e12',
        tileB: '#243a1a',
        groundDraw: drawGrassGround,
        features: [
            {
                terrain: TerrainType.FOREST,
                draw: drawTree as TerrainDrawFunction,
                noise: { scale: 0.08, threshold: 0.62 },
                isVertical: true,
            },
            {
                terrain: TerrainType.WALL,
                draw: drawMountain as TerrainDrawFunction,
                noise: { scale: 0.12, threshold: 0.78, offset: 500 },
                isBlocking: true,
                isVertical: true,
            },
        ],
    },
    DESERT: {
        tileA: '#3d2e1a',
        tileB: '#4a3820',
        groundDraw: drawSandGround,
        features: [
            {
                terrain: TerrainType.SAND,
                draw: drawSandGround as unknown as TerrainDrawFunction,
                noise: { scale: 0.05, threshold: 0.40 },
            },
            {
                terrain: TerrainType.WALL,
                draw: drawMountain as TerrainDrawFunction,
                noise: { scale: 0.15, threshold: 0.75, offset: 1000 },
                isBlocking: true,
                isVertical: true,
            },
        ],
    },
    FROZEN: {
        tileA: '#1e2a36',
        tileB: '#283848',
        groundDraw: drawSnowGround,
        features: [
            {
                terrain: TerrainType.SNOW,
                draw: drawSnowGround as unknown as TerrainDrawFunction,
                noise: { scale: 0.06, threshold: 0.45 },
            },
            {
                terrain: TerrainType.WATER,
                draw: drawWater as TerrainDrawFunction,
                noise: { scale: 0.10, threshold: 0.78, offset: 2000 },
                isBlocking: true,
            },
            {
                terrain: TerrainType.WALL,
                draw: drawMountain as TerrainDrawFunction,
                noise: { scale: 0.13, threshold: 0.80, offset: 3000 },
                isBlocking: true,
                isVertical: true,
            },
        ],
    },
};

/**
 * Get the biome config for a map type. Returns undefined for EMPTY.
 */
export function getBiomeConfig(mapType: MapType): BiomeConfig | undefined {
    return BIOME_CONFIGS[mapType];
}
